language: java

# https://docs.travis-ci.com/user/languages/java/#testing-against-multiple-jdks
jdk:
  - openjdk7
  - openjdk8
  - openjdk11

install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B
